version: "2.0"
nlu:
- intent: bot_challenge
  examples: |
    - am I talking to a human?
    - are you a human?
    - am I talking to a bot?
- intent: user_wants_to_check_upcoming_holidays
  examples: |
    - Can you please tell me about upcoming holidays
    - When is my next holiday
    - I would like to know about events for this month
    - Show me this month's holidays
- intent: question_about_clgpackage
  examples: |
    - What is the highest package?
    - about packages
    - Highest salary
    - Highest package till date
    - Highest package in ECE?
- intent: ask_faq
  examples: |
    - want to know more
    - few questions
    - i have some questions
    - some faqs
    - i have some faq
    - i want to ask some FAQs
- intent: user_wants_to_check_attendance
  examples: |
    - Please tell me about my attendance
    - Please display my attendance details
    - I would like to know how many classes have I missed
    - I want to know about my classes
    - I want to know how many classes have I missed
    - I would like to know how many classes have I attended
    - I would like to know my attendance status
- intent: user_wants_to_check_marks
  examples: |
    - I would like to know how many marks have I scored
    - I want to know how many marks I have scored
    - Please display my marks details
    - I would like to know how many marks have I missed
    - Can I know about my marks please
    - I want to know how many marks have I missed
    - Please tell me about my marks
- intent: user_wants_to_check_upcoming_exams
  examples: |
    - any exams recently
    - exam details
    - I would like to know about exams for this month
    - Can you please tell me about upcoming exams
    - Show me this month's exams
    - When is my next exam
    - about exams.
    - I want to know about exams
- intent: question_about_clg_internships
  examples: |
    - show intern detail
    - What companies come for ECE?
    - How are the college internships?
    - about internship
    - intern details
    - How many compaines come to college for internship?
    - Can I get software internship if i'm from ECE?
- intent: user_wants_utter_clg_details
  examples: |
    - details about college
    - know about college
    - location of college
    - college details
    - where is college
    - what is college email id
    - address of college
    - questions about college
- intent: user_wants_courses_available
  examples: |
    - CSE subjects
    - ECE subjects
    - about courses
    - courses?
    - subjects available
    - courses available
    - course info
    - what are the courses available?
    - would like to know about Courses
- intent: user_wants_placement_percentage
  examples: |
    - placement scenario
    - Placement percentage of ECE
    - placements details
    - know about placements
    - how much is placement
    - How many students got placed this year
    - placement so far
    - placement percentages
    - placement info
- intent: user_submitted_usn
  examples: |
    - bt18cse048
    - bt18cse042
    - bt18cse053
    - bt18cse044
    - bt18cse052
    - bt18cse041
    - bt18cse051
    - bt18cse045
    - bt18cse046
    - bt18cse047
    - bt18cse049
- intent: user_submitted_password
  examples: |
    - c0tVpk8S8x?3
    - iXeHF|x|8ZW3
    - kA=)jM3c9J)~
    - BjCv30%US9s~
    - )Bnq~0W(Q?<v
    - n(Mt6?O8o$8B
    - bz$j?eC*JKW6
    - gE3m>p2wy|J3
    - W.4@nC8)7m?Q
    - ~/1%rtA8YN)A
    - t6TY)4q(.3Fn
    - sjShBMk|8yYF
- intent: mood_great
  examples: |
    - so perfect
    - great
    - feeling like a king
    - so so perfect
    - it was perfect
    - I am feeling very good
    - I am great
    - extremely good
    - so good
    - super stoked
    - wonderful
    - i am perfect
- intent: canthelp
  examples: |
    - and that's it?
    - exit now
    - not helpful
    - i guess you can't help me then
    - that's not what i want
    - you cannot help me with what I want
    - exit
    - quit
    - that does not help
    - this is leading to nothing
    - and you call yourself bot company? pff
    - you can't help me
    - do you get anything?
    - hm i don't think you can do what i want
    - stop go back
    - I think you cant help me
    - ok then you cant help me
    - you cant help me
    - nothing else?
    - stop
- intent: thank
  examples: |
    - great thanks
    - thanks this is great news
    - thanks a bunch for everything
    - thanks for your information
    - amazing, thanks
    - thnks
    - cool, thanks
    - thanks for the help
    - Thank you
    - Great, thanks
    - thanks f
    - cheers bro
    - thank you anyways
    - thankyou
    - Cool. Thanks
    - thank u
    - thanks a lot
    - thank you
    - Thank you so much
    - ok thanks!
    - cool thanks
    - perfect thank you
    - danke
    - thanks!
    - Thank's!
    - yes thanks
    - Thanks!
    - thanks you
    - thanks
    - Thanks for that
    - ok thanks
- intent: bye
  examples: |
    - catch you later
    - gotta go
    - good bye rasa bot!
    - goodbye.
    - bye for now
    - see you . bye
    - Exit
    - byee
    - bye udo
    - k byyye #slay
    - bye bot
    - tlak to you later
    - ok, bye
    - bye .
    - adios
    - ok bye
    - Bye
    - bye
    - see you later
    - goodbye
    - bye!
    - goodnight
    - good bye
    - bye bye bot
    - bye bye
    - Close this talk
    - see you
    - cya
    - good night
    - then bye
    - byr
    - have a nice day
    - adios?
    - take care
    - good afternoon
    - Bye bye
    - toodle-oo
    - ok Bye
    - cu
- intent: mood_unhappy
  examples: |
    - extremly sad
    - You are quite bad
    - i am feel sad
    - super sad
    - boring
    - unhappy
    - you are bad bot
    - very sad
    - Now I'm sad
    - not good
    - you are bad
    - This is bad
    - my day was horrible
    - so saad
    - bots are bad
    - That tool here isnt good
    - i don't care!!!!
    - I'm super sad
    - You are rude
    - so sad
    - bad boy
    - Thats so rude
    - I'm sad
    - you make me sad
    - this is a really frustrating experience
    - iam not feeling good
    - sadly
    - i feel sad
    - i am so worry
    - i dont like bots
    - rasa is bad
    - i will leave
    - I am super sad
    - i am very sad
    - i am sad about that
    - I don't feel very well
    - I'm so sad
    - i am angry over you
    - very very sad
    - u broke my heart
    - so sad :(
    - bad
- intent: deny
  examples: |
    - no, thanks
    - no ma'am
    - no you did it wrong
    - nope!
    - Never
    - I'm not going to give it to you
    - sorry not right now
    - it sux
    - no :(
    - nope. i am good
    - I don't agree
    - nooooooooooooooooooo
    - Nopes
    - i don not like this
    - no, my frst time
    - Neither
    - this sucks
    - thanks but no thanks
    - no i don't accept
    - never mind
    - i guess it means - no
    - I don't want to give it to you
    - no I haven't decided yet if I want to sign up
    - very bad
    - not really
    - No, not really.
    - nope
    - nah, first time
    - never
    - nah, i'm good
    - no thanks
    - i don't want to give you my email
    - nein
    - I don't want to say
    - nehi
    - i don't want to
    - No thank you
    - Not really
    - still dont want to tell
    - not yet
    - no sorry
    - no thank s
    - no stop
    - no i can't
    - no I dont want
    - Nevermind
    - n
    - none of them
    - na
    - non
    - i dont want to accept :P lol
    - nö
    - no bots at all
    - no i won't
    - i decline
    - i'm afraid not
    - no i dont want to
    - it is going pretty badly
    - no and no again
    - absolutely not
    - no
    - nah I'm good
    - I don't want to
    - stop it, i do not care!!!
    - NO
    - No, thank you
    - not right now
    - i don't think so
    - NO DON"T WANT THIS!
    - decline
    - no, thankyou
    - I dont want to tell
    - not going well at all
    - neither
    - no. u r idiot
    - no sir
    - i dont want to
- intent: greet
  examples: |
    - hhola
    - what up
    - Hey
    - hi there
    - halo sara
    - hey rasa
    - Whats up?
    - Hi rasa
    - Whats up
    - hi !
    - good morning
    - Hola
    - Hello Rasa
    - HEllo
    - greetings
    - good moring
    - Heylo
    - wasssup!
    - Hi sara..
    - hi.............
    - hallo
    - hey ther
    - hi Mister
    - heya
    - howdy
    - ola sara
    - Hello Sara
    - hello
    - hi again
    - hola
    - hey hey
    - hi pal!
    - I said, helllllloooooO!!!!
    - Good Morning
    - Hi Sara!
    - hi friends
    - hlo
    - sup
    - hey there boy
    - Hey bot
    - heyo
    - hi?
    - Hi!
    - hey, let's talk
    - heelio
    - Hi, bot
    - good evening
    - Hello
    - jop
    - Hei
    - Hey Sara
    - hey dude
    - hello everybody
    - hi friend
    - hey bot
    - merhaba
    - heeey
    - heyho
    - Guten Morgen
    - hi mrs rasa
    - hello]
    - What is up?
    - rasa hello
    - Hello sara
    - hello it is me again
    - hieee
    - hello is anybody there
    - hello sara
    - HI
    - Good mourning
    - halloooo
    - jojojo
    - halo
    - hey
    - Hallo
    - ssup?
    - hey let's talk
    - hallo sara
    - hello sweatheart
    - Hi man
    - bonjour
    - Whats up my bot
    - Bom dia
    - hi folks
    - hey there
    - HEY
    - hey, sara!
    - Hieee
    - HELLO
    - hello?
    - hey there..
    - halloo
    - konichiwa
    - hiihihi
    - Hi bot
    - Hi'
    - Hi there
    - hey sara
    - HI Sara
    - Good morning
    - yoo
    - hello sweet boy
    - Hi
    - Hello!
    - hi there it's me
    - Heya
    - ey boss
    - helleo
    - hello there
    - helo
    - yo
    - Hellllooooooo
    - hai
    - wasssup
- intent: affirm
  examples: |
    - yes
    - jo
    - Wow
    - alright, cool
    - yes go for it
    - not bad
    - wow
    - okay sure
    - ok...
    - oui
    - fcourse
    - yep that's nice
    - Ok.
    - uh-huh
    - yes go ahead
    - hahaha
    - Yea
    - going super well
    - Lol
    - good.
    - you are cool man
    - yes great
    - y
    - i accept
    - More a less
    - Great information
    - ys
    - I liked the explanation
    - yeah, why not
    - Okay!
    - agreed
    - haha
    - i am!
    - you are doin great
    - yas
    - lets do this
    - yes,i am
    - that is funny
    - you are so smart
    - cool story bro
    - Yes
    - Good
    - Yes.
    - I do
    - it's pretty cool
    - I guess so
    - hm, i'd like that
    - You're cute.
    - yessoo
    - ah ok
    - ok, I behave now
    - You are great
    - ja cool
    - thats funny
    - ok cool
    - yeeees
    - yesssss
    - yaah
    - ofcoure i do
    - absolutely
    - that is cool
    - jezz
    - that's great
    - Yes please
    - yes pleae
    - really
    - well yes
    - yes that's great
    - yes please
    - thats fine
    - i will!
    - okie
    - yes I do
    - it is ok
    - i want that
    - si
    - lets do it
    - Yep that's fine
    - yeeeeezzzzz
    - awesome!
    - go ahead
    - Yepp
    - alright
    - Yes I do
    - amayzing
    - Okay
    - sure
    - You're really cool
    - I am using it
    - yes'
    - yay
    - ya thats cool
    - how nice!
    - Oh yes
    - sure!
    - love you
    - its okay
    - yes that's what i want
    - coolio
    - go
    - yyeeeh
    - hell yeah
    - I get it
    - a little
    - sure thing
    - hell yes
    - YES
    - I'm sure I will!
    - yes please!
    - yep if i have to
    - yes, cool
    - yes, I'd love to
    - Ofcourse
    - yeah sure
    - thats good
    - very much
    - I accept.
    - you are cool
    - sort of
    - ook
    - Looks nice
    - yep please
    - ya
    - yes.
    - happy
    - great lets do that
    - of course
    - yes ...
    - Awesome!
    - fair enough
    - yes accept please
    - ja
    - yup
    - thats great
    - Okay cool
    - yes sirfr
    - WOW
    - SURE
    - definitely yes without a doubt
    - PLEASE
    - okay
    - you are great
    - oh super
    - I am happy
    - yea
    - yep. :/
    - I like Rasa
    - That's awesome.
    - accept
    - yeah
    - Yeah sure
    - yap
    - ofcourse
    - you are realy intelligent
    - ha ha
    - considering
    - okay Rasabot, you're cool
    - ok friend
    - you are my new bestfriend
    - ya i want
    - Got it
    - that ok
    - i am feeling happy
    - I agree
    - ya go for it
    - Ok
    - ok, I understood
    - Yep
    - OK
    - yeah do that
    - ok good
    - Nice
    - that sounds fine
    - yes it was okay
    - yes it is
    - :D
    - cool beans
    - accepted
    - yep i want that
    - fine
    - yez
    - you seem pretty cool :D
    - awesome
    - yaps
    - ya cool
    - ok, Sara
    - such a great demo
    - sounds good!
    - yep
    - lol
    - oh awesome!
    - ya please
    - I like you
    - oh good !!
    - i agree
    - ye splease
    - great!
    - I will
    - ye
    - yres
    - fuck yeah!
    - you are a badass bot!
    - amazing!
    - rasa is awesome
    - ok..
    - top
    - k
    - kk
    - okay cool
    - You're nice.
    - Yeah
    - you are funny
    - Yup
    - Oh, ok
    - yesh
    - confirm
    - yes give me information
- synonym: english
  examples: |
    - English
    - en
    - eng
    - Eng
    - ENGLISH
- synonym: ' duration'
  examples: |
    - durations
    - how long
- synonym: USA
  examples: |
    - US
    - United States
    - U.S.
    - usa
- synonym: United Kingdom
  examples: |
    - UK
    - U.K.
- synonym: money
  examples: |
    - amounts
- synonym: organisation
  examples: |
    - companies
- synonym: name
  examples: |
    - names
- regex: greet
  examples: |
    - hey[^\s]*
