version: "2.0"
nlu:
- intent: bot_challenge
  examples: |
    - am I talking to a bot?
    - are you a bot?
    - are you a human?
- intent: user_wants_to_check_upcoming_holidays
  examples: |
    - Show me this month's holidays
    - I would like to know about events for this month
    - When is my next holiday
    - Can you please tell me about upcoming holidays
- intent: question_about_clgpackage
  examples: |
    - about packages
    - Highest package till date
    - Highest CTC
    - Highest package in CSE?
    - What is the highest package?
- intent: ask_faq
  examples: |
    - some faqs
    - i want to ask some FAQs
    - i have some faq
    - faq
    - want to know more
    - i have some questions
- intent: user_wants_to_check_attendance
  examples: |
    - I would like to know my attendance status
    - Please tell me about my attendance
    - Can I know about my attendance please
    - I want to know how many classes I have attended
    - I want to know about my classes
    - I would like to know how many classes have I missed
    - Please display my attendance details
- intent: user_wants_to_check_marks
  examples: |
    - I would like to know how many marks have I scored
    - I would like to know my marks status
    - I want to know how many marks I have scored
    - Please tell me about my marks
    - I want to know about my marks
    - Can I know about my marks please
    - I want to know how many marks have I missed
- intent: user_wants_to_check_upcoming_exams
  examples: |
    - I want to know about exams
    - any exams recently
    - Show me this month's exams
    - When is my next exam
    - when are my exams
    - Can you please tell me about upcoming exams
    - exam details
    - I would like to know about exams for this month
- intent: question_about_clg_internships
  examples: |
    - about internship
    - show intern detail
    - What companies come for ECE?
    - how about intern
    - How many compaines come to college for internship?
    - Can I get software internship if i'm from ECE?
    - intern details
- intent: user_wants_utter_clg_details
  examples: |
    - where is college
    - What is college address
    - know about college
    - college address
    - address of college
    - location of college
    - details about college
    - college details
- intent: user_wants_courses_available
  examples: |
    - about courses
    - course info
    - courses which are there
    - ECE subjects
    - would like to know about Courses
    - courses available
    - courses?
    - what are the courses available?
    - CSE subjects
- intent: user_wants_placement_percentage
  examples: |
    - placement so far
    - Placement percentage of CSE
    - placements details
    - what about placements
    - Placement percentage of ECE
    - placement percentages
    - I would like to know about Placements
    - how much is placement
    - know about placements
- intent: user_submitted_usn
  examples: |
    - bt18cse041
    - bt18cse048
    - bt18cse045
    - bt18cse053
    - bt18cse042
    - bt18cse051
    - bt18cse049
    - bt18cse046
    - bt18cse050
    - bt18cse044
    - bt18cse054
- intent: user_submitted_password
  examples: |
    - KmSD|H?8YJ7g
    - >6wR/=F%Z6Gj
    - sjShBMk|8yYF
    - n(Mt6?O8o$8B
    - gE3m>p2wy|J3
    - kA=)jM3c9J)~
    - ~/1%rtA8YN)A
    - W.4@nC8)7m?Q
    - )Bnq~0W(Q?<v
    - bz$j?eC*JKW6
    - iXeHF|x|8ZW3
    - t6TY)4q(.3Fn
- intent: mood_great
  examples: |
    - amazing
    - I am great
    - so good
    - feeling like a king
    - it was perfect
    - super stoked
    - I am feeling very good
    - great
    - extremely good
    - wonderful
    - so so perfect
    - i am perfect
- intent: canthelp
  examples: |
    - ok, but that doesnt help me
    - stop
    - hey, you promised to contact me, but nobody did, I really need to finish that car insurance bot!!!!
    - this is leading to nothing
    - you can't help me with what i need
    - stop go back
    - and you call yourself bot company? pff
    - this conversation is not really helpful
    - that does not help
    - and that's it?
    - you cannot help me with what I want
    - stop this conversation
    - ok then you cant help me
    - hm i don't think you can do what i want
    - ok i guess you can't help me
    - that's not what i want
    - exit
    - exit now
    - that was shit, you're not helping
    - you can't help me
    - I think you cant help me
    - not helping
- intent: thank
  examples: |
    - Thank's!
    - cool thank you
    - thnks
    - Thanks
    - Thank you
    - thanks for the help
    - thanks for your information
    - thanks
    - ok thanks
    - yes thanks
    - thanks this is great news
    - Great, thanks
    - great thanks
    - Thank you Sara
    - thankyou
    - thanks!
    - cheers
    - thanks a lot
    - cheers bro
    - thanks f
    - Thanks!
    - Cool. Thanks
    - thank you
    - Thanks for that
    - thank u
    - thanks for forum link, I'll check it out
    - thanks a bunch for everything
    - cool, thanks
    - perfect thank you
    - danke
    - thx
- intent: bye
  examples: |
    - toodle-oo
    - bye was nice talking to you
    - ciao
    - good by
    - cu
    - goodbye
    - have a nice day
    - see you . bye
    - good night
    - good bye
    - cya
    - bye bye
    - bye bye bot
    - gotta go
    - then bye
    - Exit
    - adios?
    - bye bot
    - bye!
    - take care
    - byee
    - cee you later
    - adios
    - bye udo
    - ok.bye
    - k byyye #slay
    - goodnight
    - catch you later
    - see you later
    - Bye
    - see u later
    - goodbye.
    - ok bye
    - ok, bye
    - bye :P
    - see you
    - Bye bye
    - Close this talk
    - ok Bye
- intent: mood_unhappy
  examples: |
    - you are bad bot
    - very sad
    - i dont like bots
    - this is a really frustrating experience
    - i'm sad
    - I am disappointed
    - I'm so sad
    - you're rather dull
    - That tool here isnt good
    - I am sad
    - I'm sad
    - so sad :(
    - very very sad
    - I am feeling bad
    - i am so worry
    - i am angry over you
    - super sad
    - I'm super sad
    - boring
    - i don't care!!!!
    - i am sad
    - i sad
    - sad
    - i am very sad
    - i will leave
    - you are bad
    - not very good
    - u broke my heart
    - I don't feel very well
    - bad boy
    - so saad
    - sadly
    - i am sad about that
    - Thats so rude
    - so sad
    - i feel sad
    - Now I'm sad
    - You are quite bad
    - not good
    - You are mad
    - I am super sad
    - rasa is bad
    - my day was horrible
- intent: deny
  examples: |
    - No thank you
    - I'm not going to give it to you
    - sorry not right now
    - no thank you
    - deny
    - no. u r idiot
    - never
    - nö
    - i dont want to
    - No.
    - stop it, i do not care!!!
    - nehi
    - Nopes
    - no stop
    - no, i hate it
    - neither
    - I don't want to say
    - i don't think so
    - I dont want to tell
    - nah
    - no, thank you
    - Never
    - no :(
    - no ma'am
    - NEIN
    - i don't want either of those
    - still dont want to tell
    - n
    - nah, first time
    - no i won't
    - never mind
    - it sucks
    - very bad
    - none of them
    - i don not like this
    - no thanks
    - it is going pretty badly
    - No, thank you
    - no i can't
    - Nah
    - I don't want to give it to you
    - nooooooooooooooooooo
    - no you did it wrong
    - no!!!!
    - noooooooooo
    - nah I'm good
    - no i dont want to accept :P lol
    - no go
    - not going well at all
    - this sucks
    - decline
    - no thank s
    - no way
    - nope. i am good
    - non
    - it sux
    - i decline
    - No, not really.
    - I'm not giving you my email address
    - I don't wanna tell the name of my company
    - no i don't accept
    - no sir
    - not right now
    - NO DON"T WANT THIS!
    - no sorry
    - no I haven't decided yet if I want to sign up
    - not yet
    - nope!
    - I don't agree
    - nein
    - Neither
    - no I dont want
    - I do not need help installing
    - i don't want to give you my email
    - nop
    - no, thanks
    - i'm afraid not
    - no and no again
    - i'm not sure
- intent: greet
  examples: |
    - hiihihi
    - hey dude
    - hey let's talk
    - hai
    - Hi Sara
    - hellooo
    - Hieeeeeeeeeeeee
    - hiii
    - heelio
    - hi again
    - hi pal!
    - hello sweet boy
    - hello?
    - hey there boy
    - Hi Sara!
    - Well hello there ;)
    - Hi sara
    - Hey
    - hi there
    - hi there it's me
    - helloooo
    - hii
    - i am [Karen Mease](name)
    - hey, let's talk
    - hello Sara
    - Bonjour
    - Hi
    - ola sara
    - halo sara
    - greet
    - hey ther
    - hello]
    - hey, sara!
    - Hi sara..
    - hallo
    - hello is anybody there
    - Hello sara
    - wasssup!
    - hi im [Amanda Anderson](name)
    - HEllo
    - yo
    - ayyyy whaddup
    - jop
    - HELLO
    - Hi man
    - Hi'
    - Heylo
    - hello there
    - Hello!
    - Guten Morgen
    - Hello Bot
    - hey rasa
    - halloooo
    - bonjour
    - hi i'm [Sandra Hernandez](name)
    - Hi,
    - Good mourning
    - hi sara
    - HI
    - hellio
    - hi Mister
    - ey boss
    - hi.............
    - hhola
    - Whats up my bot
    - What is up?
    - Good Morning
    - Whats up?
    - Hello
    - Hallo
    - wasssup
    - Hi there
    - good evening
    - Heya
    - hi
    - sup
    - Hieee
    - rasa hello
    - I said, helllllloooooO!!!!
    - hey sara
    - halloo
    - Hello Sara
    - hi?
    - hey there
    - hallo sara
    - whats popping
    - Hei
    - what up
    - hlo
    - hola
    - hey hey
    - heyo
    - hey bot!
    - hi friend
    - heya
    - Good morning
    - heyho
    - Hi rasa
    - hello robot
    - hi mrs rasa
    - hello friend
    - hello sweatheart
    - hello, my name is [Charles Pfeffer](name)
    - salut
    - HI Sara
    - Hello Rasa
    - good morning
    - hi folks
    - hey
    - howdy
    - hi can you speak ?
    - helleo
    - merhaba
    - greetings
    - Hi!
    - jojojo
    - hell9o
    - Hellllooooooo
- intent: affirm
  examples: |
    - today was a nice day
    - oki doki
    - yes pls
    - ah ok
    - you are funny
    - Yeah sure
    - go
    - okay Rasabot, you're cool
    - k
    - jezz
    - you asked me a yes or no question, which i answered with yes
    - that's great
    - yes it is
    - ja cool
    - such a great demo
    - awesome
    - yesssss
    - oh super
    - you seem pretty cool :D
    - fuck yeah!
    - Looks nice
    - Good
    - I'm using it
    - please
    - okay..
    - fair enough
    - i agree
    - yes
    - Yup
    - oh cool
    - you are great
    - it is ok
    - love you
    - lets do it
    - ok friend
    - yeeees
    - well yes
    - si
    - Sure
    - sounds good!
    - you are cool
    - yes.
    - ja
    - PLEASE
    - That would be great
    - ha ha
    - yesh
    - Awesome!
    - yeah sure
    - oh good !!
    - yes accept please
    - that was a great interaction
    - yep thats cool
    - you got me, I accept, if you want me to
    - not bad
    - yes go ahead
    - Yepp
    - thats good
    - yeah'=
    - yep. :/
    - fcourse
    - yes great
    - rasa is awesome
    - ye
    - amazing!
    - yep, will do thank you
    - Yep that's fine
    - OK
    - yup
    - YES
    - ok fine
    - kk
    - yeeeeezzzzz
    - it's pretty cool
    - alright
    - ok, Sara
    - lets do this
    - yes cool
    - yres
    - y
    - ok good
    - great lets do that
    - yes,i am
    - ok cool
    - how nice!
    - sort of
    - yes i agree
    - hèhè
    - considering
    - ok, I behave now
    - yyeeeh
    - Yes please
    - That's awesome.
    - i am feeling happy
    - Great
    - perfect
    - Cool
    - yep i want that
    - fine
    - Accept
    - yes of course
    - yes that's great
    - ya please
    - yeah, why not
    - Okay!
    - yaah
    - Ofcourse
    - yes please
    - cool :)
    - Oh yes
    - yeah
    - accept
    - yas
    - that sounds fine
    - yes it was okay
    - Got it
    - Yep
    - yez
    - oh awesome!
    - done
    - ya
    - yesss
    - I changed my mind. I want to accept it
    - going super well
    - yap
    - cool beans
    - yop
    - you are my new bestfriend
    - cool!
    - thats fine
    - LOL
    - I will
    - yeah do that
    - yay
    - yes, give me information, please
    - good.
    - alright, cool
    - jo
    - coolio
    - I agree
    - you are doin great
    - sure!
    - i am happy today
    - you are so smart
    - HAHA
    - Ok
    - i will!
    - great!
    - of course
    - ys
    - cool story bro
    - confirm
    - yes, cool
    - top
    - thats great
    - that is funny
    - Ok.
    - yess
    - yes give me information
    - ok
    - yep if i have to
    - yes, I'd love to
    - ook
    - yes i have built a bot before
    - hahaha
    - You're really cool
    - Nice
    - you are awesome
    - i accept
    - i am happy
    - I like you
    - agreed
    - ya cool
    - happy
    - yes ...
    - yea
    - ok i accept
    - yes go for it
    - yep please
    - great
    - ok great
    - Yes I do
    - i am!
    - ok, I understood
    - yes you can
    - yes that's what i want
    - Okay
    - haha
    - Yep!
    - absolutely
    - lol
    - you are a badass bot!
    - You're nice.
    - ofcourse
    - SURE
    - I am happy
    - I accept
    - go ahead
    - I have used it in the past
    - YUP
    - okay sure
    - Oh, ok
    - I'm sure I will!
    - accepted
    - ya i want
    - cool
    - I'd absolutely love that
    - yes i accept
    - Sweet
    - very much
    - Lol thats funny
    - definitely yes without a doubt
    - I like Rasa
    - I guess so
    - I do
    - I am using it
    - Lol
    - yesyesyes
    - i love you
    - hell yeah
    - ja thats great
    - i want that
    - I accept.
    - okie
    - a little
    - Yea
    - Yes, I accept
    - okay
    - Okay cool
- synonym: english
  examples: |
    - English
    - en
    - eng
    - Eng
    - ENGLISH
- synonym: ' duration'
  examples: |
    - durations
    - how long
- synonym: USA
  examples: |
    - US
    - United States
    - U.S.
    - usa
- synonym: United Kingdom
  examples: |
    - UK
    - U.K.
- synonym: money
  examples: |
    - amounts
- synonym: organisation
  examples: |
    - companies
- synonym: name
  examples: |
    - names
- regex: greet
  examples: |
    - hey[^\s]*
