version: "2.0"
nlu:
- intent: bot_challenge
  examples: |
    - are you a bot?
    - am I talking to a human?
    - are you a human?
- intent: user_wants_to_check_upcoming_holidays
  examples: |
    - Can you please tell me about upcoming holidays
    - Show me this month's holidays
    - I want to know about holidays
    - When is my next holiday
- intent: question_about_clgpackage
  examples: |
    - What is the highest package?
    - Highest package till date
    - Highest package in ECE?
    - Highest CTC
    - about packages
- intent: ask_faq
  examples: |
    - few questions
    - want to know more
    - i have some faq
    - i have some questions
    - faq
    - i want to ask some FAQs
- intent: user_wants_to_check_attendance
  examples: |
    - I want to know about my classes
    - Can I know about my attendance please
    - Please display my attendance details
    - I want to know how many classes have I missed
    - I want to know how many classes I have attended
    - I would like to know my attendance status
    - I would like to know how many classes have I missed
- intent: user_wants_to_check_marks
  examples: |
    - Please tell me about my marks
    - Can I know about my marks please
    - I want to know how many marks have I missed
    - I would like to know my marks status
    - I would like to know how many marks have I scored
    - I would like to know how many marks have I missed
    - I want to know about my marks
- intent: user_wants_to_check_upcoming_exams
  examples: |
    - Can you please tell me about upcoming exams
    - exam details
    - When is my next exam
    - any exams recently
    - when are my exams
    - Show me this month's exams
    - I would like to know about exams for this month
    - I want to know about exams
- intent: question_about_clg_internships
  examples: |
    - What companies come for ECE?
    - How many compaines come to college for internship?
    - show intern detail
    - Does college provide inrernships?
    - How are the college internships?
    - how about intern
    - about internship
- intent: user_wants_utter_clg_details
  examples: |
    - details about college
    - questions about college
    - college details
    - college address
    - location of college
    - What is college address
    - address of college
    - where is college
- intent: user_wants_courses_available
  examples: |
    - number of courses
    - courses available
    - courses which are there
    - CSE subjects
    - courses?
    - what are the courses available?
    - subjects available
    - would like to know about Courses
    - course info
- intent: user_wants_placement_percentage
  examples: |
    - placement so far
    - I would like to know about Placements
    - How many students got placed this year
    - placement scenario
    - Placement percentage of CSE
    - what about placements
    - how much is placement
    - placements details
    - placement percentages
- intent: user_submitted_usn
  examples: |
    - bt18cse043
    - bt18cse042
    - bt18cse049
    - bt18cse051
    - bt18cse048
    - bt18cse053
    - bt18cse046
    - bt18cse052
    - bt18cse044
    - bt18cse047
    - bt18cse054
- intent: user_submitted_password
  examples: |
    - DnBeoWKo
    - NAZoEYOD
    - pLpWguSz
    - dTdiUpMi
    - XIjTYiVD
    - TbpBXuJC
    - EasyPasS
    - HDamVuKd
    - MMjzmQyt
    - JYoDQrES
    - nEqTMlyU
    - LNAVNENt
- intent: mood_great
  examples: |
    - wonderful
    - amazing
    - so good
    - I am feeling very good
    - it was perfect
    - I am amazing
    - I am going to save the world
    - I am great
    - i am perfect
    - feeling like a king
    - so perfect
    - extremely good
- intent: canthelp
  examples: |
    - that was shit, you're not helping
    - and you call yourself bot company? pff
    - ok i guess you can't help me
    - stop
    - ok then you cant help me
    - nothing else?
    - this is leading to nothing
    - you can't help me
    - you cant help me
    - this conversation is not really helpful
    - do you get anything?
    - stop this conversation
    - that's not what i want
    - you can't help me with what i need
    - ok, but that doesnt help me
    - and that's it?
    - hm i don't think you can do what i want
    - hey, you promised to contact me, but nobody did, I really need to finish that car insurance bot!!!!
    - quit
    - that does not help
- intent: thank
  examples: |
    - perfect thank you
    - ok thanks!
    - Thank you
    - thanks
    - Cool. Thanks
    - danke
    - Thanks!
    - thanks a lot
    - thank you anyways
    - thanks you
    - thank you
    - great thanks
    - Thank you Sara
    - cool thank you
    - cheers
    - cheers bro
    - thanks for forum link, I'll check it out
    - thanks a bunch for everything
    - Great, thanks
    - thankyou
    - Thank's!
    - yes thanks
    - cool, thanks
    - cool thanks
    - Thanks bot
    - thanks for your information
    - thx
    - Thank you so much
    - thanks!
    - thank u
    - thanks this is great news
    - Thanks
- intent: bye
  examples: |
    - byr
    - bye bye
    - gotta go
    - ok.bye
    - goodnight
    - Exit
    - farewell
    - goodbye.
    - see you . bye
    - see u later
    - bye udo
    - bye .
    - bye bye bot
    - Bye
    - bye!
    - good bye
    - bye bot
    - good afternoon
    - see ya
    - see you later
    - ok, bye
    - bye
    - byee
    - toodle-oo
    - have a nice day
    - ok bye
    - cu
    - good by
    - adios
    - catch you later
    - Close this talk
    - ciao
    - cya
    - then bye
    - good bye rasa bot!
    - adios?
    - tlak to you later
    - ok Bye
    - good night
- intent: mood_unhappy
  examples: |
    - i feel sad
    - You are mad
    - I am disappointed
    - u broke my heart
    - very very sad
    - sad
    - That tool here isnt good
    - i am sad
    - this is a really frustrating experience
    - not very good
    - sadly
    - i am very sad
    - so saad
    - I don't feel very well
    - I am super sad
    - you make me sad
    - you are bad
    - crappy joke
    - so sad :(
    - bad
    - i sad
    - so sad
    - you are bad bot
    - I'm super sad
    - very sad
    - I am sad
    - my day was horrible
    - Thats so rude
    - You are rude
    - you're rather dull
    - i am feel sad
    - bad boy
    - unhappy
    - iam not feeling good
    - I'm so sad
    - extremly sad
    - i dont like bots
    - not good
    - i'm sad
    - super sad
    - This is bad
    - i am angry over you
- intent: deny
  examples: |
    - nein
    - no, i hate it
    - no ma'am
    - none of them
    - i don't want either of those
    - no and no again
    - nope
    - Never
    - no go
    - nah, first time
    - i don not like this
    - not yet
    - I'm not giving you my email address
    - nooooooooooooooooooo
    - no i don't accept
    - NEIN
    - NO
    - no!!!!
    - no i can't
    - no, my frst time
    - decline
    - no i dont want to
    - no :(
    - no I dont want
    - thanks but no thanks
    - I do not need help installing
    - very bad
    - no stop
    - it is going pretty badly
    - i guess it means - no
    - No, thank you
    - absolutely not
    - i dont want to
    - I don't want to say
    - Nopes
    - no thank you
    - NO DON"T WANT THIS!
    - I don't want to
    - i dont want to accept :P lol
    - no way
    - it sux
    - I don't want to give it to you
    - deny
    - Not really
    - no. u r idiot
    - no thanks
    - nah
    - Neither
    - not really
    - i don't want to
    - no you did it wrong
    - nö
    - neither
    - i decline
    - no, thank you
    - non
    - no bots at all
    - still dont want to tell
    - nah not for me
    - definitely not
    - nop
    - noooooooooo
    - no, thankyou
    - sorry not right now
    - i don't want to give you my email
    - no
    - No thank you
    - nah I'm good
    - no i dont want to accept :P lol
    - nehi
    - nope. i am good
    - no I haven't decided yet if I want to sign up
    - I dont want to tell
    - this sucks
    - i'm not sure
    - No, not really.
    - not right now
    - i'm afraid not
    - Nevermind
- intent: greet
  examples: |
    - hey ther
    - heya
    - hi Mister
    - Good Morning
    - ssup?
    - whats up
    - rasa hello
    - hello Sara
    - Hieeeeeeeeeeeee
    - helo
    - HEllo
    - Hello Sara
    - heyo
    - hiihihi
    - hey there boy
    - what up
    - hell9o
    - Hi there
    - hey there
    - Hi'
    - hola
    - halo
    - hlo
    - hey, let's talk
    - Good morning
    - heeey
    - hello robot
    - HEY
    - Heylo
    - salut
    - hi.............
    - jop
    - wasssup!
    - Whats up my bot
    - jojojo
    - Hey Sara
    - Bonjour
    - hey hey
    - hi there
    - I said, helllllloooooO!!!!
    - hiii
    - hello sweet boy
    - hello hi
    - Hey
    - Good mourning
    - Hei
    - heyho
    - hii
    - hi !
    - sup
    - halloooo
    - hi pal!
    - good moring
    - i am [Karen Mease](name)
    - hello everybody
    - Hi Sara!
    - hello]
    - howdy
    - hi there it's me
    - hello is anybody there
    - hey, sara!
    - Hi!
    - hello world
    - heelio
    - Hallo
    - hi i'm [Sandra Hernandez](name)
    - Hello Bot
    - hi can you speak ?
    - hi friends
    - hey there..
    - Hi, bot
    - Hieee
    - hi again
    - whats popping
    - merhaba
    - hey let's talk
    - hi sara
    - hi friend
    - Hi man
    - Hellllooooooo
    - wasssup
    - hello there
    - hellio
    - yo
    - halo sara
    - hieee
    - bonjour
    - hello sara
    - Whats up?
    - yoo
    - HELLO
    - Hola
    - hi mrs rasa
    - Heya
    - hey dude
    - hello
    - Hello!
    - Hello sara
    - Whats up
    - Bom dia
    - hello it is me again
    - greet
    - Hi,
    - hhola
    - hey sara
    - Hey bot
    - Hi sara
    - ola sara
    - hi im [Amanda Anderson](name)
    - Hi sara..
    - Hi Sara
    - hello friend
    - hello?
    - hey bot!
    - halloo
    - hi folks
    - hello sweatheart
    - hey rasa
- intent: affirm
  examples: |
    - ok great
    - coolio
    - that's great
    - Okay cool
    - yes give me information
    - YES
    - Yup
    - how nice!
    - i love you
    - Oh, ok
    - yes, give me information, please
    - you are so smart
    - yez
    - great
    - I do
    - yessoo
    - I will
    - I mean to say that I liked the explanation
    - oh cool
    - SURE
    - si
    - ya please
    - yess
    - yep please
    - yesh
    - absolutely
    - Looks nice
    - ok
    - sure!
    - considering
    - that sounds fine
    - I guess so
    - please
    - yes great
    - YUP
    - Accept
    - yes i accept
    - confirm
    - great!
    - ok...
    - yes i have!
    - rasa is awesome
    - :)
    - you asked me a yes or no question, which i answered with yes
    - yeah do that
    - yesss
    - awesome!
    - cool beans
    - ja
    - I'd absolutely love that
    - Ok let's start
    - ya cool
    - ys
    - oui
    - yop
    - More a less
    - y
    - you seem pretty cool :D
    - that ok
    - oh awesome!
    - yes that's what i want
    - :D
    - I accept
    - yes pleae
    - ye
    - okay cool
    - yes i have built a bot before
    - yeeees
    - i will!
    - ya i want
    - I am happy
    - today was a nice day
    - sort of
    - yesyesyes
    - i am very happy with your response
    - Yep!
    - ah ok
    - yay
    - I have used it in the past
    - definitely yes without a doubt
    - yes go for it
    - yes I do
    - ye splease
    - yes baby
    - yes it is
    - Yes please
    - Ofcourse
    - Ok
    - amayzing
    - i am feeling happy
    - yes'
    - I love you
    - ok, I understood
    - fair enough
    - ok cool
    - wow
    - yep
    - I get it
    - Cool
    - yaah
    - agreed
    - you good
    - i am happy today
    - hell yeah
    - alright
    - cool story bro
    - going super well
    - yes, cool
    - go for it
    - ok good
    - k
    - sure thing
    - love you
    - yeah
    - accepted
    - ok sara
    - Nice
    - you are cool man
    - I changed my mind. I want to accept it
    - yup
    - you are cool
    - hèhè
    - Lol
    - that is cool
    - hm, i'd like that
    - Sweet
    - like u
    - accept
    - lets do it
    - you are realy intelligent
    - yes go ahead
    - yep if i have to
    - yes i agree
    - thats great
    - Wow
    - I'm sure I will!
    - ofcourse
    - a little
    - yyeeeh
    - ya thats cool
    - Great information
    - yap
    - hahah
    - kk
    - LOL
    - yes please!
    - amazing!
    - Good
    - ofcoure i do
    - hahaha
    - you are great
    - That's awesome.
    - okay Rasabot, you're cool
    - it's pretty cool
    - that is funny
    - perfect
    - ok i accept
    - oh good !!
    - Yes.
    - Sure
    - happy
    - yeah'=
    - Yep that's fine
    - well yes
    - yep, will do thank you
    - yes please
    - Yeah sure
    - i want that
    - fcourse
    - thats fine
    - yas
    - WOW
    - Yea
    - Yes, I accept
    - yes.
    - ja thats great
    - hAHAHA
    - i accept
    - yeah, why not
    - fuck yeah!
    - cool!
    - ok, Sara
    - yes of course
    - very much
    - i am!
    - you are doin great
    - such a great demo
    - Awesome!
    - ok..
    - thats funny
    - OK
    - I accept.
    - yes,i am
    - sure
    - you are funny
    - alright, cool
    - sounds good!
    - ook
    - ya
    - yes, I'd love to
    - cool :)
    - yesssss
    - You're really cool
    - okay sure
    - Okay!
    - yeah sure
    - good.
    - done
    - okie
    - Yes I do
    - I am using it
    - go
    - Yeah
    - yres
    - great lets do that
    - yes cool
    - ok friend
    - haha
    - hell yes
    - lol
    - Oh yes
    - thats good
    - yes
    - its okay
    - ya go for it
    - PLEASE
    - jezz
    - That would be great
    - go ahead
    - You are great
- synonym: english
  examples: |
    - English
    - en
    - eng
    - Eng
    - ENGLISH
- synonym: ' duration'
  examples: |
    - durations
    - how long
- synonym: USA
  examples: |
    - US
    - United States
    - U.S.
    - usa
- synonym: United Kingdom
  examples: |
    - UK
    - U.K.
- synonym: money
  examples: |
    - amounts
- synonym: organisation
  examples: |
    - companies
- synonym: name
  examples: |
    - names
- regex: greet
  examples: |
    - hey[^\s]*
